// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using JobInformationAPI.Models;

namespace JobInformationAPI.Data
{
    public partial class TodoDBContext : DbContext
    {
        public TodoDBContext()
        {
        }

        public TodoDBContext(DbContextOptions<TodoDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CountryInfo> CountryInfos { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<JobInformation> JobInformations { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Information>(entity =>
            {
                entity.HasOne(d => d.Country)
                    .WithMany(p => p.Information)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_Information_CountryInfo");

                entity.HasOne(d => d.Job)
                    .WithMany(p => p.Information)
                    .HasForeignKey(d => d.JobId)
                    .HasConstraintName("FK_Information_JobInformation");
            });

            modelBuilder.Entity<JobInformation>(entity =>
            {
                entity.Property(e => e.MinimunExperience).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}