// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JobInformationAPI.Models
{
    [Table("CountryInfo")]
    public partial class CountryInfo
    {
        public CountryInfo()
        {
            Information = new HashSet<Information>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Unicode(false)]
        public string CountryName { get; set; }

        [InverseProperty("Country")]
        public virtual ICollection<Information> Information { get; set; }
    }
}