// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JobInformationAPI.Models
{
    [Table("JobInformation")]
    public partial class JobInformation
    {
        public JobInformation()
        {
            Information = new HashSet<Information>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Unicode(false)]
        public string JobName { get; set; }
        public bool? ReqExperience { get; set; }
        [StringLength(10)]
        public string MinimunExperience { get; set; }

        [InverseProperty("Job")]
        public virtual ICollection<Information> Information { get; set; }
    }
}